# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTables', '0002_person_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('eng_name', models.CharField(max_length=10)),
                ('hp', models.CharField(default=0, max_length=10)),
                ('hpperlevel', models.CharField(default=0, max_length=10)),
                ('hpregen', models.CharField(default=0, max_length=10)),
                ('hpregenperlevel', models.CharField(default=0, max_length=10)),
                ('mp', models.CharField(default=0, max_length=10)),
                ('mpperlevel', models.CharField(default=0, max_length=10)),
                ('mpregen', models.CharField(default=0, max_length=10)),
                ('mpregenperlevel', models.CharField(default=0, max_length=10)),
                ('movespeed', models.CharField(default=0, max_length=10)),
                ('attackdamage', models.CharField(default=0, max_length=10)),
                ('attackdamageperlevel', models.CharField(default=0, max_length=10)),
                ('attackspeedoffset', models.CharField(default=0, max_length=10)),
                ('attackspeedperlevel', models.CharField(default=0, max_length=10)),
                ('attackrange', models.CharField(default=0, max_length=10)),
                ('armor', models.CharField(default=0, max_length=10)),
                ('armorperlevel', models.CharField(default=0, max_length=10)),
                ('spellblock', models.CharField(default=0, max_length=10)),
                ('spellblockperlevel', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
