# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 01:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTables', '0003_champion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='champion',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 24, 1, 49, 21, 213134, tzinfo=utc), verbose_name='update date'),
        ),
    ]
