# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTables', '0005_auto_20170324_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='eng_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='champion',
            name='update_date',
            field=models.DateTimeField(verbose_name='update date'),
        ),
    ]
