# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTables', '0007_auto_20170327_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='armor',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='armorperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackdamage',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackdamageperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackrange',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackspeedoffset',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackspeedperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpregen',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='hpregenperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='movespeed',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpregen',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='mpregenperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='spellblock',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='spellblockperlevel',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
