# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTables', '0008_auto_20170327_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='armormax',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='attackdamagemax',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='hpmaxmax',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='hpregenmax',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='mpmax',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='mpregenmax',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='champion',
            name='spellblockmax',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
