# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTables', '0009_auto_20170327_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='hpmaxmax',
            new_name='hpmax',
        ),
    ]
