# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTables', '0010_auto_20170327_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='attackspeedoffset',
        ),
        migrations.AddField(
            model_name='champion',
            name='attackspeed',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='attackrange',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='champion',
            name='movespeed',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
