# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
